[package]
name = "oneui/backendtemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
replica = "ivasmigins/replica@0.1.0"

[dev-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"
